/**
 * Uebernommen aus design-system.md, Kapitel 11 «Tailwind-Konfiguration».
 * Ergaenzt wurde ausschliesslich das fuer Tailwind technisch notwendige `content`-Feld.
 * Keine eigenen Farben, Abstaende, Radien oder Schriftgroessen.
 */
/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      // Semantic (nur diese im Markup verwenden!)
      text: {
        primary: 'var(--text-primary)',
        secondary: 'var(--text-secondary)',
        tertiary: 'var(--text-tertiary)',
        disabled: 'var(--text-disabled)',
        brand: 'var(--text-brand)',
        decorative: 'var(--text-decorative)',
        'nav-selected': 'var(--text-nav-selected)',
        'on-colored-bg': 'var(--text-on-colored-bg)',
        'on-interactive-primary': 'var(--text-on-interactive-primary)',
        'on-interactive-disabled': 'var(--text-on-interactive-disabled)',
      },
      interactive: {
        primary: 'var(--interactive-primary)',
        'primary-hover': 'var(--interactive-primary-hover)',
        secondary: 'var(--interactive-secondary)',
        disabled: 'var(--interactive-disabled)',
        'primary-on-colored-bg': 'var(--interactive-primary-on-colored-bg)',
        'primary-on-colored-bg-hover': 'var(--interactive-primary-on-colored-bg-hover)',
        'disabled-on-colored-bg': 'var(--interactive-disabled-on-colored-bg)',
      },
      background: {
        device: 'var(--background-device)',
        card: 'var(--background-card)',
        'subtle-neutral': 'var(--background-subtle-neutral)',
        'medium-neutral': 'var(--background-medium-neutral)',
        brand: 'var(--background-brand)',
        hover: 'var(--background-hover)',
        'decorative-light': 'var(--background-decorative-light)',
        overlay: 'var(--background-overlay)',
        'overlay-darker': 'var(--background-overlay-darker)',
        'white-overlay': 'var(--background-white-overlay)',
        'white-overlay-darker': 'var(--background-white-overlay-darker)',
      },
      border: {
        DEFAULT: 'var(--border)',
        light: 'var(--border-light)',
        focus: 'var(--border-focus)',
        card: 'var(--border-card)',
        'on-colored-bg': 'var(--border-on-colored-bg)',
      },
      constant: { black: 'var(--constant-black)', white: 'var(--constant-white)' },
      status: {
        info: 'var(--status-info)',
        success: 'var(--status-success)',
        warning: 'var(--status-warning)',
        error: 'var(--status-error)',
        notification: 'var(--status-notification)',
        'text-info': 'var(--status-text-info)',
        'text-success': 'var(--status-text-success)',
        'text-warning': 'var(--status-text-warning)',
        'text-error': 'var(--status-text-error)',
        'light-bg-info': 'var(--status-light-bg-info)',
        'light-bg-success': 'var(--status-light-bg-success)',
        'light-bg-warning': 'var(--status-light-bg-warning)',
        'light-bg-error': 'var(--status-light-bg-error)',
        'text-info-on-light-bg': 'var(--status-text-info-on-light-bg)',
        'text-success-on-light-bg': 'var(--status-text-success-on-light-bg)',
        'text-warning-on-light-bg': 'var(--status-text-warning-on-light-bg)',
        'text-error-on-light-bg': 'var(--status-text-error-on-light-bg)',
      },
      decorative: {
        'pink-light': 'var(--decorative-pink-light)',
        'pink-medium': 'var(--decorative-pink-medium)',
        pink: 'var(--decorative-pink)',
        'pink-darker': 'var(--decorative-pink-darker)',
        'purple-light': 'var(--decorative-purple-light)',
        'purple-medium': 'var(--decorative-purple-medium)',
        purple: 'var(--decorative-purple)',
        'purple-darker': 'var(--decorative-purple-darker)',
        'blue-light': 'var(--decorative-blue-light)',
        'blue-medium': 'var(--decorative-blue-medium)',
        blue: 'var(--decorative-blue)',
        'blue-darker': 'var(--decorative-blue-darker)',
        'yellow-light': 'var(--decorative-yellow-light)',
        'yellow-medium': 'var(--decorative-yellow-medium)',
        yellow: 'var(--decorative-yellow)',
        'yellow-darker': 'var(--decorative-yellow-darker)',
        'green-light': 'var(--decorative-green-light)',
        'green-medium': 'var(--decorative-green-medium)',
        green: 'var(--decorative-green)',
        'green-darker': 'var(--decorative-green-darker)',
        'ecru-light': 'var(--decorative-ecru-light)',
        'ecru-medium': 'var(--decorative-ecru-medium)',
        ecru: 'var(--decorative-ecru)',
        'ecru-darker': 'var(--decorative-ecru-darker)',
      },
    },
    spacing: {
      none: '0',
      ant: '2px',
      bee: '4px',
      snail: '8px',
      frog: '12px',
      rat: '16px',
      chicken: '20px',
      cat: '24px',
      dog: '32px',
      donkey: '40px',
      gorilla: '48px',
      lion: '56px',
      grizzly: '64px',
      rhino: '80px',
      elephant: '96px',
    },
    borderRadius: {
      none: '0',
      DEFAULT: '2px',
      sm: '2px',
      md: '4px',
      lg: '6px',
      xl: '8px',
      '2xl': '16px',
      full: '9999px',
    },
    borderWidth: { 0: '0px', DEFAULT: '1px', s: '1px', m: '2px', l: '4px' },
    boxShadow: {
      s: '0px 1px 4px 0px rgba(0,0,0,0.16)',
      m: '1px 6px 20px -8px rgba(0,0,0,0.12)',
      'm-hover': '1px 12px 24px -12px rgba(0,0,0,0.32)',
      l: '0px 4px 32px -8px rgba(0,0,0,0.16)',
      'l-hover': '0px 8px 40px -12px rgba(0,0,0,0.32)',
      border: '0px 12px 16px -8px rgba(0,0,0,0.16)',
    },
    fontFamily: { sans: ['"Akkurat Helsana"', '"Helvetica Neue"', 'Arial', 'sans-serif'] },
    fontWeight: { light: '300', normal: '400', bold: '700' },
    screens: { mobile: '375px', tablet: '768px', desktop: '1024px' },
    extend: { maxWidth: { layout: '1280px' } },
  },
};
